# http://knanma.com/parlor?m=16
# 스크롤 로딩을 감않나 동적 페이지 크롤링 필요 - 궁여지책으로 일단 복붙
import pandas as pd
import re
import requests
from bs4 import BeautifulSoup
from tqdm import tqdm


#response = requests.get(
#    f"http://knanma.com/parlor?m=16",
#    headers={
#        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36",
#        "referer": "http://knanma.com/parlor?m=16"
#    },
#)  # headers need to pass firewall
#assert response.status_code == 200
## make BS parse object
#bs_obj = BeautifulSoup(response.text, "html.parser")
## get table contents
#bs_obj = bs_obj.find("section", class_="contents_wrap")
#bs_obj = bs_obj.find("div", id="apps")
#bs_obj = bs_obj.find("div", class_="view-container")
#print(bs_obj)
#
#bs_obj = bs_obj.find("div", class_="shop-area")
#
#bs_obj = bs_obj.find("div", class_="shop-wrap")
#
#bs_obj = bs_obj.find("ul", class_="shop-list")
#
#print(bs_obj)
#
#table_list = []
#for t in bs_obj.table.thead.find_all("tr"):
#    cols = [i.text.strip() for i in t.find_all("th")]
#    table_list.append(cols)
#for t in bs_obj.table.tbody.find_all("tr"):
#    cols = [i.text.strip() for i in t.find_all("td")]
#    table_list.append(cols)
#
#df = pd.DataFrame(table_list[1:], columns=table_list[0])
#df.fillna("", inplace=True)
#
#print(df)

response_text = """
<ul class="shop-list"><li class="shop-item"><a href="/parlor/view?m=16&amp;id=250"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/images/content/shop01.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>7.08km</span></div> <div class="shop-item-name"><h3>조은안마원</h3></div> <div class="shop-item-address">
  경남 창원시 성산구 마디미서로 54
</div> <div class="shop-item-type"><p>대표:조수용,장헌철</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">60,000</p></div></div> <div class="star_wrap"><ul class="star_list"> <li class="star_item"><img src="/images/common/star.svg" alt="0"></li><li class="star_item"><img src="/images/common/star.svg" alt="0"></li><li class="star_item"><img src="/images/common/star.svg" alt="0"></li><li class="star_item"><img src="/images/common/star.svg" alt="0"></li><li class="star_item"><img src="/images/common/star.svg" alt="0"></li></ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=249"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/202208/1659683351_cbf93f3fe9f353827f6b.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>51.21km</span></div> <div class="shop-item-name"><h3>최선생안마원</h3></div> <div class="shop-item-address">
  경남 진주시 진주역로 114
</div> <div class="shop-item-type"><p>대표:최명식</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">50,000</p></div></div> <div class="star_wrap"><ul class="star_list"> <li class="star_item"><img src="/images/common/star.svg" alt="0"></li><li class="star_item"><img src="/images/common/star.svg" alt="0"></li><li class="star_item"><img src="/images/common/star.svg" alt="0"></li><li class="star_item"><img src="/images/common/star.svg" alt="0"></li><li class="star_item"><img src="/images/common/star.svg" alt="0"></li></ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=248"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/202208/1659682900_3b2c8bd3896e708d7083.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>54.29km</span></div> <div class="shop-item-name"><h3>제일약손안마원</h3></div> <div class="shop-item-address">
  경남 사천시 사천읍 정의길 41
</div> <div class="shop-item-type"><p>대표:임태환</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">50,000</p></div></div> <div class="star_wrap"><ul class="star_list"> <li class="star_item"><img src="/images/common/star.svg" alt="0"></li><li class="star_item"><img src="/images/common/star.svg" alt="0"></li><li class="star_item"><img src="/images/common/star.svg" alt="0"></li><li class="star_item"><img src="/images/common/star.svg" alt="0"></li><li class="star_item"><img src="/images/common/star.svg" alt="0"></li></ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=226"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/202203/1647997260_d783ca4113a57f255be9.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>38.26km</span></div> <div class="shop-item-name"><h3>바른몸약손안마원(밀양)</h3></div> <div class="shop-item-address">
  경남 밀양시 내이2길 8
</div> <div class="shop-item-type"><p>대표:하세인</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">50,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=223"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/223/1641885132_3614345690115f4ad4c0.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>2.13km</span></div> <div class="shop-item-name"><h3>건암물리지압원</h3></div> <div class="shop-item-address">
  경남 창원시 진해구 동진로 56-4
</div> <div class="shop-item-type"><p>대표:노재두</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">50,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=217"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/images/content/shop01.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>90.63km</span></div> <div class="shop-item-name"><h3>함양안마원</h3></div> <div class="shop-item-address">
  경남 함양군 수동면 수동1길 172
</div> <div class="shop-item-type"><p>대표:문찬석</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">40,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=206"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/206/1632450783_97d0d805c67d3dd04b5c.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>31.68km</span></div> <div class="shop-item-name"><h3>홍선생안마원</h3></div> <div class="shop-item-address">
  경남 창녕군 남지읍 동포7길 9
</div> <div class="shop-item-type"><p>대표:홍수용</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">50,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=205"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/205/1632450663_9a3fd28e5c318a3bbd06.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>54.40km</span></div> <div class="shop-item-name"><h3>참편안안마원</h3></div> <div class="shop-item-address">
  경남 진주시 의곡길 3
</div> <div class="shop-item-type"><p>대표:정의창</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">50,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=204"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/images/content/shop01.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>51.49km</span></div> <div class="shop-item-name"><h3>진주지압안마센터</h3></div> <div class="shop-item-address">
  경남 진주시 돗골로94번길 6
</div> <div class="shop-item-type"><p>대표:김종환</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">40,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=200"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/200/1632450212_dcff47e9b597e5194879.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>42.23km</span></div> <div class="shop-item-name"><h3>건강안마원</h3></div> <div class="shop-item-address">
  경남 의령군 의령읍 의병로15길 3
</div> <div class="shop-item-type"><p>대표:조우현</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">50,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=199"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/199/1632450104_7c3bb7e66bce5642d08e.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>52.40km</span></div> <div class="shop-item-name"><h3>주원전통안마원</h3></div> <div class="shop-item-address">
  경남 양산시 삼호동부로 39
</div> <div class="shop-item-type"><p>대표:황용기</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">60,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=198"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/198/1632449948_ec43e2a72d0ff799db6a.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>38.06km</span></div> <div class="shop-item-name"><h3>정유섬지압원</h3></div> <div class="shop-item-address">
  경남 양산시 양주3길 11-10
</div> <div class="shop-item-type"><p>대표:정유섬</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">50,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=197"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/197/1632449357_27de43f24aa76cf37229.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>38.75km</span></div> <div class="shop-item-name"><h3>이곳생명샘지압안마원</h3></div> <div class="shop-item-address">
  경남 양산시 북안남3길 23
</div> <div class="shop-item-type"><p>대표:송향옥</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">50,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=196"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/196/1632449147_e94eacf65caa3807443d.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>36.10km</span></div> <div class="shop-item-name"><h3>약손건강안마원</h3></div> <div class="shop-item-address">
  경남 양산시 동면 금오4길 66
</div> <div class="shop-item-type"><p>대표:박종일</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">50,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=195"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/images/content/shop01.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>11.53km</span></div> <div class="shop-item-name"><h3>창원안마원</h3></div> <div class="shop-item-address">
  경남 창원시 의창구 도계로 102
</div> <div class="shop-item-type"><p>대표:김미자</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">40,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=194"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/194/1632448970_abc53d8273b095e51a4d.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>34.38km</span></div> <div class="shop-item-name"><h3>라파지압안마원</h3></div> <div class="shop-item-address">
  경남 양산시 물금읍 청운로 185
</div> <div class="shop-item-type"><p>대표:조형섭</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">0</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=193"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/193/1632449091_dc2014c2cc33f5f607d5.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>9.32km</span></div> <div class="shop-item-name"><h3>명인안마지압센터</h3></div> <div class="shop-item-address">
  경남 창원시 성산구 원이대로393번길 25
</div> <div class="shop-item-type"><p>대표:이영우</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">70,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=192"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/192/1632449075_c68a513cec12f817187a.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>7.26km</span></div> <div class="shop-item-name"><h3>두드림안마센터</h3></div> <div class="shop-item-address">
  경남 창원시 성산구 용지로 74
</div> <div class="shop-item-type"><p>대표:김은미</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">60,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=191"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/191/1632449041_786d3e4de19a6f303bf1.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>7.04km</span></div> <div class="shop-item-name"><h3>바른안마원</h3></div> <div class="shop-item-address">
  경남 창원시 성산구 상남동 73-4
</div> <div class="shop-item-type"><p>대표:남철조</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">48,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> <li class="star_item"><img src="/images/common/star.svg" alt="0"></li></ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=190"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/190/1642567508_6d976d6470c4c9189756.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>7.12km</span></div> <div class="shop-item-name"><h3>윤안마원</h3></div> <div class="shop-item-address">
  경남 창원시 성산구 마디미로31번길 10
</div> <div class="shop-item-type"><p>대표:윤영주</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">50,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=189"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/189/1632448967_1fd8d5f5388a81b1f9f6.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>12.65km</span></div> <div class="shop-item-name"><h3>화타의손안마원</h3></div> <div class="shop-item-address">
  경남 창원시 마산회원구 합성옛길 271
</div> <div class="shop-item-type"><p>대표:성정훈</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">60,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=188"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/188/1632448928_6781fd898cf70c88f556.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>11.21km</span></div> <div class="shop-item-name"><h3>행복한지압원</h3></div> <div class="shop-item-address">
  경남 창원시 마산회원구 용마로 126
</div> <div class="shop-item-type"><p>대표:박현제</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">60,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=187"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/187/1632448902_000e8138a0baa45d8557.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>12.41km</span></div> <div class="shop-item-name"><h3>제일안마센터</h3></div> <div class="shop-item-address">
  경남 창원시 마산회원구 양덕로 193
</div> <div class="shop-item-type"><p>대표:유순애</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">50,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=186"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/186/1632448883_a97aa5f70a92e4156527.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>11.01km</span></div> <div class="shop-item-name"><h3>전통안마지압센터</h3></div> <div class="shop-item-address">
  경남 창원시 마산회원구 삼호로 36
</div> <div class="shop-item-type"><p>대표:하영옥</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">50,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> <li class="star_item"><img src="/images/common/star.svg" alt="0"></li></ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=185"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/185/1632448862_9ad1c67cd7d4e6d5d0bc.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>11.90km</span></div> <div class="shop-item-name"><h3>한효안마센터</h3></div> <div class="shop-item-address">
  경남 창원시 마산회원구 북성로 118
</div> <div class="shop-item-type"><p>대표:이영주</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">42,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=184"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/184/1632448841_c9d64e8346cb83088ed9.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>17.99km</span></div> <div class="shop-item-name"><h3>기룡안마지압센터</h3></div> <div class="shop-item-address">
  경남 창원시 마산합포구 진동면 서촌숲끝길 16
</div> <div class="shop-item-type"><p>대표:황동순</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">50,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=183"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/183/1632448815_0513cb1689d4c412c1a0.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>11.23km</span></div> <div class="shop-item-name"><h3>정일품안마통증관리</h3></div> <div class="shop-item-address">
  경남 창원시 마산합포구 오동서17길 10-16
</div> <div class="shop-item-type"><p>대표:박정택</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">60,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=181"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/181/1632386412_49bf2141e8e68041454a.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>59.56km</span></div> <div class="shop-item-name"><h3>사계절건강지압안마원</h3></div> <div class="shop-item-address">
  경남 사천시 벌리2길 7
</div> <div class="shop-item-type"><p>대표:김남곤</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">50,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=180"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/180/1632386425_f70c5a65c16cc3678d68.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>12.25km</span></div> <div class="shop-item-name"><h3>마이더스안마원</h3></div> <div class="shop-item-address">
  경남 창원시 의창구 반계로 103
</div> <div class="shop-item-type"><p>대표:김병주</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">0</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=179"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/179/1632386463_8fc21e9378f5d6c38751.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>17.85km</span></div> <div class="shop-item-name"><h3>약손안마원</h3></div> <div class="shop-item-address">
  경남 창원시 의창구 북면 감계리 234-2
</div> <div class="shop-item-type"><p>대표:이권우</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">40,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=178"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/178/1632386656_b7ae3ce16143cdea39c2.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>8.50km</span></div> <div class="shop-item-name"><h3>편강안마센터</h3></div> <div class="shop-item-address">
  경남 창원시 성산구 상남로 246
</div> <div class="shop-item-type"><p>대표:송채은</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">60,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=177"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/images/content/shop01.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>8.21km</span></div> <div class="shop-item-name"><h3>백세안마원</h3></div> <div class="shop-item-address">
  경남 창원시 성산구 신월로 8
</div> <div class="shop-item-type"><p>대표:백원갑</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">50,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=176"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/176/1632385780_1981dc67fb5375a3fc72.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>11.23km</span></div> <div class="shop-item-name"><h3>핸드테크 지압원</h3></div> <div class="shop-item-address">
  경남 창원시 마산합포구 성호남1길 21
</div> <div class="shop-item-type"><p>대표:김동철</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">80,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=175"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/175/1632385730_c1802c3f8b7d1e08a84c.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>11.04km</span></div> <div class="shop-item-name"><h3>건강찾기안마원</h3></div> <div class="shop-item-address">
  경남 창원시 마산합포구 반월동1길 18
</div> <div class="shop-item-type"><p>대표:임정남</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">50,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=174"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/174/1632385855_b36fd8da412899857ab1.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>54.52km</span></div> <div class="shop-item-name"><h3>강안마지압원</h3></div> <div class="shop-item-address">
  경남 사천시 사천읍 사천읍성로 16
</div> <div class="shop-item-type"><p>대표:강상우</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">40,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=173"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/173/1632385897_a0ce618e35de98484759.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>11.79km</span></div> <div class="shop-item-name"><h3>정선생지압안마원</h3></div> <div class="shop-item-address">
  경남 김해시 번화1로68번길 7
</div> <div class="shop-item-type"><p>대표:정환종</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">60,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=172"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/172/1632385440_9dab8d0f5d241f9c7fc9.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>9.84km</span></div> <div class="shop-item-name"><h3>편한몸안마원</h3></div> <div class="shop-item-address">
  경남 창원시 의창구 원이대로 283
</div> <div class="shop-item-type"><p>대표:김명애</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">50,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=171"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/171/1641887754_52fe374dc13df5a73d7a.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>11.45km</span></div> <div class="shop-item-name"><h3>장유힐링지압원</h3></div> <div class="shop-item-address">
  경남 김해시 능동로7번길 8-23
</div> <div class="shop-item-type"><p>대표:양동식</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">50,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=170"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/170/1632386734_8f6745e3dd4c430f2542.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>12.37km</span></div> <div class="shop-item-name"><h3>팔팔안마원</h3></div> <div class="shop-item-address">
  경남 창원시 의창구 팔용로 420
</div> <div class="shop-item-type"><p>대표:유나경</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">50,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=169"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/169/1632386043_a95a35ecee22ab495401.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>19.14km</span></div> <div class="shop-item-name"><h3>웰빙지압원</h3></div> <div class="shop-item-address">
  경남 김해시 함박로119번길 18
</div> <div class="shop-item-type"><p>대표:박광범</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">35,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=168"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/168/1641952380_badc7124409517ab3f88.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>21.19km</span></div> <div class="shop-item-name"><h3>성보수기안마원</h3></div> <div class="shop-item-address">
  경남 김해시 활천로16번길 9
</div> <div class="shop-item-type"><p>대표:장성보</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">0</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=167"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/167/1632386776_01e369baaf0b7d671bbc.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>12.19km</span></div> <div class="shop-item-name"><h3>현안마원</h3></div> <div class="shop-item-address">
  경남 창원시 의창구 평산로159번길 9
</div> <div class="shop-item-type"><p>대표:이현</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">55,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=166"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/166/1642140675_c62ffe4e8b7dcb535db3.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>13.49km</span></div> <div class="shop-item-name"><h3>실로암안마지압원</h3></div> <div class="shop-item-address">
  경남 창원시 진해구 용재로 11-1
</div> <div class="shop-item-type"><p>대표:민종철</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">50,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=165"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/165/1632386113_8403c1aea7b64abab57b.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>19.09km</span></div> <div class="shop-item-name"><h3>보성안마원</h3></div> <div class="shop-item-address">
  경남 김해시 내외중앙로 44
</div> <div class="shop-item-type"><p>대표:김우철</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">55,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=164"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/164/1632386962_99d4d8a26406cb4385dd.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>3.88km</span></div> <div class="shop-item-name"><h3>더조은안마원</h3></div> <div class="shop-item-address">
  경남 창원시 진해구 충장로657번길 28
</div> <div class="shop-item-type"><p>대표:김윤관</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">70,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=163"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/163/1632388357_7a2de96acfe725861012.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>38.97km</span></div> <div class="shop-item-name"><h3>바른몸약손안마원</h3></div> <div class="shop-item-address">
  경남 통영시 광도면 죽림2로 76-163
</div> <div class="shop-item-type"><p>대표:배성진</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">60,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=162"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/162/1632388445_8be4e1eaf78cdc712b87.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>42.45km</span></div> <div class="shop-item-name"><h3>참좋은지압안마센터</h3></div> <div class="shop-item-address">
  경남 통영시 새터길 18
</div> <div class="shop-item-type"><p>대표:김문환</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">50,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=161"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/images/content/shop01.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>43.28km</span></div> <div class="shop-item-name"><h3>통영지압안마원</h3></div> <div class="shop-item-address">
  경남 통영시 당동길 4
</div> <div class="shop-item-type"><p>대표:서윤상</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">50,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=160"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/160/1632388488_bebc49f7f218ec651be4.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>27.90km</span></div> <div class="shop-item-name"><h3>무병장수안마원</h3></div> <div class="shop-item-address">
  경남 함안군 가야읍 가야10길 13
</div> <div class="shop-item-type"><p>대표:박성남</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">50,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> <li class="star_item"><img src="/images/common/star.svg" alt="0"></li></ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=159"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/159/1632386159_fa3bdb4691b34db566a6.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>20.23km</span></div> <div class="shop-item-name"><h3>백세건강지압원</h3></div> <div class="shop-item-address">
  경남 김해시 가락로93번길 7
</div> <div class="shop-item-type"><p>대표:정종남</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">50,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=158"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/158/1632386192_ad22e9ae8626732ed1fb.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>19.09km</span></div> <div class="shop-item-name"><h3>로뎀지압원</h3></div> <div class="shop-item-address">
  경남 김해시 내외중앙로 44
</div> <div class="shop-item-type"><p>대표:이복금</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">50,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=157"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/157/1632386221_196b2ca575c6367da302.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>17.06km</span></div> <div class="shop-item-name"><h3>라파지압원</h3></div> <div class="shop-item-address">
  경남 김해시 진영읍 여래로 27
</div> <div class="shop-item-type"><p>대표:정원열</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">60,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=156"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/156/1632386262_8ef8dc522712859ed12e.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>37.97km</span></div> <div class="shop-item-name"><h3>한국안마센터</h3></div> <div class="shop-item-address">
  경남 고성군 고성읍 중앙로25번길 76
</div> <div class="shop-item-type"><p>대표:윤태호</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">30,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=155"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/155/1632386290_4c7eaad15604174e42f3.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>28.96km</span></div> <div class="shop-item-name"><h3>햇빛안마클리닉</h3></div> <div class="shop-item-address">
  경남 거제시 옥포로 250
</div> <div class="shop-item-type"><p>대표:이명옥</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">40,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li><li class="shop-item"><a href="/parlor/view?m=16&amp;id=154"><div class="shop-item-wrap"><div class="shop-item-img_box"><img src="/files/user/image/154/1632388560_c67d76d2e03a141fbdcb.jpg" onerror="this.src='/images/content/shop01.jpg'" alt="이미지"></div> <div class="shop-item-box"><div class="shop-item-box_wrap"><div class="shop-item-content"><div class="shop-item-top"><span>65.36km</span></div> <div class="shop-item-name"><h3>최용석지압안마원</h3></div> <div class="shop-item-address">
  경남 합천군 합천읍 중앙로 33-32
</div> <div class="shop-item-type"><p>대표:최용석</p></div></div> <div class="shop-item-sale-box"><p class="shop-item-sale-03">50,000</p></div></div> <div class="star_wrap"><ul class="star_list"><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li><li class="star_item"><img src="/images/common/star_color.svg" alt="1"></li> </ul></div></div></div></a></li></ul>
"""
table_list = []
table_list.append(["name", "addr", "owner", "link"])
bs_obj = BeautifulSoup(response_text, "html.parser")
for t in bs_obj.find_all("a"):
    link = "http://knanma.com" + t["href"].strip()  # http://knanma.com/parlor/view?id=xxx

    t = t.find("div", class_="shop-item-wrap")
    t = t.find("div", class_="shop-item-box")
    t = t.find("div", class_="shop-item-box_wrap")
    t = t.find("div", class_="shop-item-content")
    
    name = t.find("div", class_="shop-item-name").text.strip()
    addr = t.find("div", class_="shop-item-address").text.strip()
    owner = t.find("div", class_="shop-item-type").text[3:].strip()
    table_list.append([name, addr, owner, link])

df = pd.DataFrame(table_list[1:], columns=table_list[0])
df.fillna("", inplace=True)    
df.to_csv("../regions/GyeongsangSouth.csv")
